config/routes.rb
Rails.application.routes.draw do

root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/embed/:id', to: 'users#embed'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token
	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

   def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	after_action :allow_iframe, only: :embed
protect_from_forgery with: :exception
  include SessionsHelper


private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
    flash.now[:danger] = 'Invalid email/password combination' 
	    # Create an error message.
      render 'new'
    end
  end

  def destroy
	  log_out
	  redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])
	  if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  def embed
    @user = User.find(params[:id])
    render 'embed'
	  #show embed url
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :themecolor, :bgcolor, :innercolor, 
				   :headtextcolor, :textcolor, :buttonbg, :buttontext)
    end

     def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

 def log_in(user)
    session[:user_id] = user.id
  end

# Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
     # if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
# Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  def logged_in?
    !current_user.nil?
  end

# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
	  forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
		    <li><%= link_to "Profile", current_user %></li>
		    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= yield(:title) %> | Memorial App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
	    'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html> 
<head>

<style>

* {
	margin: 0;
	padding: 0;
	border: 0;
}

body {
	background: #fbfbfb;
	color: #67727A;
	font-family: 'Alegreya', Sans-serif;
	margin: 0;
}

#header-inner{
	background: #fbfbfb;
}

h2{
	font-size: 300%;
	font-weight: 900; 
	text-align: left;
	padding-top: 2%;
}
h3{
	font-size: 175%;
	line-height: 155%;
	padding:2% 0;
	font-weight: 400;
}
p {
	font-size: 100%;
	line-height: 150%;
	padding: 3%;
	text-indent: 2%;
	text-align: justify;
}

.one-third{
	width: 33.33333333%;
	float: left;
	text-align: center;
}

#create {
	background-color:#bdbbba;
}

#cherish {
	background-color: #bf9d85;
}

#commemorate{
	background-color: #a59f8c;
}

.partners{
	width: 33.33333333%;
	float: left;
	text-align: center;
}

#partner-one {
	background-color: #dff1f4;
	border-style: solid;
		border-width: 1px;
		border-color: #ffffff;
}

#partner-two{
	background-color: #dff1f4;
border-style: solid;
		border-width: 1px;
		border-color: #ffffff;
}

#partner-three{
	background-color: #dff1f4;
border-style: solid;
		border-width: 1px;
border-color: #ffffff;
}

/*--- Start Navigation--*/
nav {
	float: right;
	padding: 30px 20px 0 0;
}
#menu-icon {
	display: hidden;
	width: 40px;
	height: 40px;;
}
a:hover#menu-icon{
	border-radius: 4px 4px 0 0;
}

ul{
	list-style-type: none;
}

nav ul li{
	font-family: 'Alegreya Sans', Sans-serif;
	font-size: 150%;
	display: inline-block;
	float: left;
	padding: 10px;
}
nav ul li a{
	color: #445c37;
	text-decoration: none;
}
nav ul li a:hover{
	color: #0f2d6d;
}
.current{
	color: #627485;
}

/*---Navigation end--*/

footer{
	background-color: #f6f6f6;
	width: 100%;
}

.more-info{
 	list-style-type: none;
	text-align: left;
 }
 .more-info li{
	 display: inline;
 }
 .more-info i{
 	font-size: 460%;
 	margin: 1%;
 	padding: 4%;
 	color: #C3D7DF;
 }

.more-info i:hover{
	color: #F5F5F5;
}

footer ul li{

	display: inline-block;
	float: left;
	padding: 10px;
}
footer ul li a{
	text-decoration: none;
}

footer.sub ul li{
	display: block;
}



/*--- Button --*/

#Facebook{
	background-color: #1535a5;
	color: white;
}

#Sign-up{
	background-color: #3a4244;
	color: #eee9e3;
}

/* Generic Button Styles */

  .button{
    padding:8px 12px;
    background:#0A5175;
    display: block;
    width:120px;
    margin:10px 0 0px 0;
    border-radius:3px;
    -webkit-transition: all 0.3s;
    -moz-transition: all 0.3s;
    transition: all 0.3s;
    text-align:center;
    font-size:0.8em;
    box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
    -moz-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
    -webkit-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
  }

  .button:hover{
    background:#8BC3A3;
    color:white;
  }


</style>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>timeless</title>
	<link rel="stylesheet" type="text/css" href="style.css" />	
	<link href="css/font-awesome.min.css" rel="stylesheet"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<header>
		<div id="header-inner">
			<nav>
			<a href="#" id="menu-icon"></a>
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Sign in", login_path %></li>
				<li><%= link_to "Sign up", signup_path %></li>
			</ul>
			</nav>
			<section class="title" id="title">
				<td><i class="glyphicon glyphicon-hourglass"></i></td>
				<h2>Timeless</h2>
				<h3>Eternal memories cherised forever</h3>	
			</section>

				<div class="input-group">
            	<input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
            	<div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            	</div>
        		</div>


				<a href="https://www.facebook.com" target="_blank"><button onclick ="" id="Facebook">Connect with Facebook</button></a>
				<br>
				<button onclick="" id="Sign-up">Create Memorial</button>
				</div>
				
			</section>
		</div>
	</header>
	<!---End Header-->

		<section class="one-third" id="create">
			<h4>Create</h4>
			<td><i class="glyphicon glyphicon-user"></i></td>
			<p>insert long text here</p>
		</section>

		<section class="one-third" id="cherish">
			<h4>Cherish</h4>
			<td><i class="glyphicon glyphicon-heart-empty"></i></td>
			<p>insert long text here</p>
		</section>

		<section class="one-third" id="commemorate">
			<h4>Commemorate</h4>
			<td><i class="glyphicon glyphicon-grain"></i></td>
			<p>insert long text here</p>
		</section>

<!---End Three Column Section-->

		<section class="partners" id="partner-one">
			<img src="">
			<h5>Faith Bereavement</h5>
		</section>

		<section class="partners" id="partner-two">
			<img src="">
			<h5>Ang Yew Seng Funeral Palour</h5>
		</section>

		<section class="partners" id="partner-three">
			<img src="">
			<h5>Singapore Indian Casket Services</h5>
		</section>

<!---End Partners Section-->

            </div><!-- End Inner -->
	</aside>

	</section>

	<footer>

		<ul class="more-info">

			<li class="sub"><h4>About</h4>
			<ul>
			<li><a href="https://www.facebook.com" target="_blank">Using Timeless</a></li>
			<li><a href="https://www.facebook.com" target="_blank">Examples</a></li>
			</li>
			</ul>

			<ul>
			<li class="sub"><h4>Contact</h4>
			<li><a href="https://www.google.com" target="_blank">Partnerships</a></li>
			<li><a href="https://www.google.com" target="_blank">Contact Us</a></li>
			</li>
			</ul>

			<ul>
			<li class="sub"><h4>Support</h4>
			<li><a href="" target="_blank">FAQ</a></li>
			<li><a href="" target="_blank">Suite Service</a></li>
			</li>
			</ul>

			<li class="sub"><h4>Information</h4>
			<ul>
			<li><a href="https://www.youtube.com" target="_blank">Privacy & Security</a></li>
			<li><a href="https://www.youtube.com" target="_blank">Terms of Service</a></li>
			</li>
			</ul>

		</ul>
	</footer>
<!---End of footer section-->

</body>
</html>

		

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label:date_of_birth %>
			<%= f.date_select :date_of_birth, class: 'form-control' %>

			<div>
				<%= f.check_box :is_female, {}, true %> <%= f.label :is_female, "Female" %>
				<%= f.check_box :is_female, {}, false %> <%= f.label :is_female, "Male" %>
			</div>

			<%= f.label:themecolor, "Choose theme color" %>
			<%= f.color_field :themecolor, class: 'form-control' %>

			<%= f.label:bgcolor, "Choose background color"  %>
			<%= f.color_field :bgcolor, class: 'form-control' %>

			<%= f.label:innercolor, "Choose inner background color" %>
			<%= f.color_field :innercolor, class: 'form-control' %>

			<%= f.label:headtextcolor, "Choose header texts color" %>
			<%= f.color_field :headtextcolor, class: 'form-control' %>

			<%= f.label:textcolor, "Choose text color" %>
			<%= f.color_field :textcolor, class: 'form-control' %>

			<%= f.label:buttontext, "Choose button's text color" %>
			<%= f.color_field :buttontext, class: 'form-control' %>

			<%= f.label:buttonbg, "Choose button's fill color" %>
			<%= f.color_field :buttonbg, class: 'form-control' %>



			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>


			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>

	</div>
</div>

app/views/users/embed.html.erb
<html>
<head>
<body>
<style>

.personal-info {
  background-color: #e8ecf2;
}

h2 {
  font-weight: bold;
  color: #3d434c;
  font-size: 24px;
}

h4 {
  color: #53575e;
  font-size: 15px;
}

</style>

<div class="text-center profileimg">
          <img class="img-profile-square" style="background-color:white;display:inline-block;" src="https://memorialweb.s3.amazonaws.com/assets/listing/picture/17/e9f508f2-664c-48c1-a4e1-6f8f23d3a389_display.png" alt="E9f508f2 664c 48c1 a4e1 6f8f23d3a389 display" />
        
  </div>

  <div class="personal-info">
  <h2 class="margin-top-sm"><%= @user.name %></h2>

  <h4 class="text-center text-light"><%= @user.email %></h4>
  <h4 class="text-center text-light"><strong>Departed: </strong>Wednesday, 8th February 2017</h4>
   <h4 class="text-center text-light"><strong>Age: </strong>89</h4>
  <hr>
</div>



</body>
</head>
</html>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
	<% @users.each do |user| %>
		<%= render user %>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>